export enum EFeatureKey {
  POST_JOB = 'POST_JOB',
  SEARCH_CANDIDATE = 'SEARCH_CANDIDATE',
  PINNED_JOB = 'PINNED_JOB',
  HIGHLIGHT_JOB = 'HIGHLIGHT_JOB',
  ACCESS_ALL_CVS = 'ACCESS_ALL_CVS',
  MULTI_USER_ACCOUNT = 'MULTI_USER_ACCOUNT',
}
